name = "goteo-v4-frontend"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-06-26"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
keep_vars = true

[assets]
binding = "ASSETS"
directory = "./dist"

[observability.logs]
enabled = true

[env.b4m]
routes = [
    { pattern = "crowdfunding.b4m.space", zone_name = "b4m.space", custom_domain = true },
]